[app]
ginLogPath = 'logs/gin.log'
secretKey = '\x0f"V!\xe5\x94\x9a\x1c\\\x9fj\x1a\xf2\xcca\xe3\x99\xf9\x1as\xe0\xdb\x9c\xb3'

[server]
runMode = 'debug'
httpPort = 7000
readTimeout = 60
writeTimeout = 60

[database]
type = 'mysql'
host = '127.0.0.1:3306'
name = 'market'
user = 'root'
password = '111111'




